Traceback (most recent call last):
  File "/Users/jvanscho/miniforge3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/jvanscho/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/jvanscho/miniforge3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/jvanscho/miniforge3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/jvanscho/miniforge3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/jvanscho/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/Users/jvanscho/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/jvanscho/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# General imports
%matplotlib inline
from preamble import *
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOptionError[0m                               Traceback (most recent call last)
[0;32m/var/folders/0t/5d8ttqzd773fy0wq3h5db0xr0000gn/T/ipykernel_69736/482805016.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# General imports[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0mget_ipython[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mrun_line_magic[0m[0;34m([0m[0;34m'matplotlib'[0m[0;34m,[0m [0;34m'inline'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0;32mfrom[0m [0mpreamble[0m [0;32mimport[0m [0;34m*[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/Documents/mlcourse/master/studies/preamble.py[0m in [0;36m<module>[0;34m[0m
[1;32m     29[0m [0;34m[0m[0m
[1;32m     30[0m [0mpd[0m[0;34m.[0m[0mset_option[0m[0;34m([0m[0;34m"display.max_columns"[0m[0;34m,[0m [0;36m8[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 31[0;31m [0mpd[0m[0;34m.[0m[0mset_option[0m[0;34m([0m[0;34m'precision'[0m[0;34m,[0m [0;36m2[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     32[0m [0;34m[0m[0m
[1;32m     33[0m [0mnp[0m[0;34m,[0m [0mmglearn[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniforge3/lib/python3.9/site-packages/pandas/_config/config.py[0m in [0;36m__call__[0;34m(self, *args, **kwds)[0m
[1;32m    254[0m [0;34m[0m[0m
[1;32m    255[0m     [0;32mdef[0m [0m__call__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwds[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 256[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m__func__[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwds[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    257[0m [0;34m[0m[0m
[1;32m    258[0m     [0;34m@[0m[0mproperty[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniforge3/lib/python3.9/site-packages/pandas/_config/config.py[0m in [0;36m_set_option[0;34m(*args, **kwargs)[0m
[1;32m    147[0m [0;34m[0m[0m
[1;32m    148[0m     [0;32mfor[0m [0mk[0m[0;34m,[0m [0mv[0m [0;32min[0m [0mzip[0m[0;34m([0m[0margs[0m[0;34m[[0m[0;34m:[0m[0;34m:[0m[0;36m2[0m[0;34m][0m[0;34m,[0m [0margs[0m[0;34m[[0m[0;36m1[0m[0;34m:[0m[0;34m:[0m[0;36m2[0m[0;34m][0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 149[0;31m         [0mkey[0m [0;34m=[0m [0m_get_single_key[0m[0;34m([0m[0mk[0m[0;34m,[0m [0msilent[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    150[0m [0;34m[0m[0m
[1;32m    151[0m         [0mo[0m [0;34m=[0m [0m_get_registered_option[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniforge3/lib/python3.9/site-packages/pandas/_config/config.py[0m in [0;36m_get_single_key[0;34m(pat, silent)[0m
[1;32m    114[0m         [0;32mraise[0m [0mOptionError[0m[0;34m([0m[0;34mf"No such keys(s): {repr(pat)}"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    115[0m     [0;32mif[0m [0mlen[0m[0;34m([0m[0mkeys[0m[0;34m)[0m [0;34m>[0m [0;36m1[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 116[0;31m         [0;32mraise[0m [0mOptionError[0m[0;34m([0m[0;34m"Pattern matched multiple keys"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    117[0m     [0mkey[0m [0;34m=[0m [0mkeys[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m    118[0m [0;34m[0m[0m

[0;31mOptionError[0m: 'Pattern matched multiple keys'
OptionError: 'Pattern matched multiple keys'

